#!/usr/bin/env python3
"""Numbers freeze: summary.csv -> LaTeX tables and a prose-number ledger.

PLAN.md P8: no number is hand-typed anywhere in the v2 paper. Every table cell and every
percentage in the prose is produced here from summary.csv rows, each of which carries the
commit and the full CLI that produced it.

Three refusals are deliberate and are the point of the script:

  * It REFUSES to pool rows from different commits unless --allow-mixed-commits is given.
    "Never pool arms from different binaries" is a standing project rule; a table that
    silently mixes builds is how a defective-geometry number ends up beside a corrected one.
  * It REFUSES rows with dirty=1 unless --allow-dirty. A row whose tree was dirty cannot be
    reproduced from its commit hash, so it cannot appear in a paper.
  * It drops rows with status != OK or track_success != 1 from the statistics and reports
    them as the success rate instead. KITTI 08/09 appear as failures, never as absences
    (PLAN.md P5).

Usage
    make_tables.py --csv runs/wp6 --out paper/tables
    make_tables.py --csv runs/wp6 runs/wp4 --out paper/tables --allow-mixed-commits
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from collections import defaultdict
from pathlib import Path
from statistics import median


def _f(v):
    try:
        x = float(v)
        return x if math.isfinite(x) else None
    except (TypeError, ValueError):
        return None


def load_rows(paths: list[Path]) -> list[dict]:
    rows = []
    for p in paths:
        files = sorted(p.rglob("summary.csv")) if p.is_dir() else [p]
        for f in files:
            with open(f, newline="") as fh:
                for r in csv.DictReader(fh):
                    r["_src"] = str(f)
                    rows.append(r)
    return rows


def iqr(vals: list[float]) -> float:
    if len(vals) < 2:
        return float("nan")
    s = sorted(vals)
    n = len(s)

    def q(p):
        i = p * (n - 1)
        lo, hi = int(math.floor(i)), int(math.ceil(i))
        return s[lo] if lo == hi else s[lo] + (s[hi] - s[lo]) * (i - lo)

    return q(0.75) - q(0.25)


AGG_FIELDS = ("ate_sim3_rmse", "ate_se3_rmse", "scale_s", "pipeline_fps", "track_fps",
              "scale_drift_pct_per_100m", "rpe_trans", "rpe_rot",
              "peak_gpu_mb", "peak_cpu_mb", "ml_ms")


def aggregate(rows: list[dict]) -> dict:
    """Median + IQR per (arm, dataset, sequence), over usable reps only."""
    groups: dict[tuple, list[dict]] = defaultdict(list)
    for r in rows:
        groups[(r["arm"], r["dataset"], r["sequence"])].append(r)

    out = {}
    for key, reps in groups.items():
        ok = [r for r in reps if r.get("status") == "OK" and r.get("track_success") == "1"]
        cell = {"n": len(reps), "n_ok": len(ok),
                "success_rate": len(ok) / len(reps) if reps else 0.0}
        for field in AGG_FIELDS:
            vals = [v for v in (_f(r.get(field)) for r in ok) if v is not None]
            cell[field] = median(vals) if vals else float("nan")
            cell[field + "_iqr"] = iqr(vals) if vals else float("nan")
        cell["lc_gate_fires_total"] = sum(
            int(r["lc_gate_fires"]) for r in ok if str(r.get("lc_gate_fires", "")).isdigit())
        out[key] = cell
    return out


def fmt(x, prec=3, dash="--"):
    if x is None or (isinstance(x, float) and not math.isfinite(x)):
        return dash
    return f"{x:.{prec}f}"


def _esc(s: str) -> str:
    return s.replace("_", r"\_")


def latex_main_table(agg: dict, arms: list[str], label: str, caption: str) -> str:
    seqs = sorted({(d, s) for (a, d, s) in agg if a in arms})
    head = " & ".join(rf"\multicolumn{{3}}{{c}}{{{_esc(a)}}}" for a in arms)
    sub = " & ".join([r"ATE$_{Sim3}$ & ATE$_{SE3}$ & $s$"] * len(arms))
    lines = [
        "% GENERATED by run_scripts/ral_v2/make_tables.py -- do not edit by hand",
        r"\begin{table}[t]\centering",
        rf"\caption{{{caption}}}\label{{{label}}}",
        r"\begin{tabular}{ll" + "rrr" * len(arms) + "}",
        r"\toprule",
        rf"Dataset & Seq. & {head} \\",
        rf" &  & {sub} \\",
        r"\midrule",
    ]
    for d, s in seqs:
        cells = []
        for a in arms:
            c = agg.get((a, d, s))
            if not c or c["n_ok"] == 0:
                cells += [r"\textit{fail}", r"\textit{fail}", "--"]
            else:
                cells += [fmt(c["ate_sim3_rmse"]), fmt(c["ate_se3_rmse"]), fmt(c["scale_s"])]
        lines.append(f"{d} & {_esc(s)} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def latex_ablation_table(agg: dict, baseline: str, label: str, caption: str) -> str:
    arms = sorted({a for (a, _, _) in agg})
    lines = [
        "% GENERATED by run_scripts/ral_v2/make_tables.py -- do not edit by hand",
        r"\begin{table}[t]\centering",
        rf"\caption{{{caption}}}\label{{{label}}}",
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        rf"Arm & med. ATE$_{{Sim3}}$ & IQR & med. $s$ & success & $\Delta$ vs {_esc(baseline)} \\",
        r"\midrule",
    ]
    base = {(d, s): c["ate_sim3_rmse"]
            for (a, d, s), c in agg.items() if a == baseline and c["n_ok"]}

    for a in arms:
        cells = [c for (aa, _, _), c in agg.items() if aa == a and c["n_ok"]]
        if not cells:
            continue
        ate = [c["ate_sim3_rmse"] for c in cells if math.isfinite(c["ate_sim3_rmse"])]
        sc = [c["scale_s"] for c in cells if math.isfinite(c["scale_s"])]
        sr = sum(c["success_rate"] for c in cells) / len(cells)
        # Paired by sequence against the baseline -- never a ratio of pooled means.
        deltas = [(c["ate_sim3_rmse"] / base[(d, s)] - 1) * 100
                  for (aa, d, s), c in agg.items()
                  if aa == a and c["n_ok"] and (d, s) in base and base[(d, s)]
                  and math.isfinite(c["ate_sim3_rmse"])]
        dtxt = rf"{median(deltas):+.1f}\%" if deltas and a != baseline else "--"
        lines.append(
            f"{_esc(a)} & {fmt(median(ate) if ate else None)} & "
            f"{fmt(median([c['ate_sim3_rmse_iqr'] for c in cells]))} & "
            f"{fmt(median(sc) if sc else None)} & {sr * 100:.0f}\\% & {dtxt} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv", nargs="+", required=True, help="summary.csv files or dirs to scan")
    ap.add_argument("--out", required=True)
    ap.add_argument("--baseline", default="A0")
    ap.add_argument("--main-arms", nargs="+", default=["A0", "full"])
    ap.add_argument("--allow-mixed-commits", action="store_true")
    ap.add_argument("--allow-dirty", action="store_true")
    a = ap.parse_args()

    rows = load_rows([Path(p) for p in a.csv])
    if not rows:
        print("ERROR: no rows found", file=sys.stderr)
        return 2

    dirty = [r for r in rows if r.get("dirty") == "1"]
    if dirty and not a.allow_dirty:
        print(f"ERROR: {len(dirty)} row(s) came from a dirty working tree and so cannot be\n"
              f"       reproduced from their commit hash. Re-run them, or pass --allow-dirty\n"
              f"       for a draft. Example: {dirty[0]['_src']}", file=sys.stderr)
        return 3
    if not a.allow_dirty:
        rows = [r for r in rows if r.get("dirty") != "1"]

    commits = sorted({r.get("commit", "?") for r in rows})
    if len(commits) > 1 and not a.allow_mixed_commits:
        print(f"ERROR: rows span {len(commits)} commits {commits}. Arms from different binaries\n"
              f"       are not poolable. Re-run at one commit, or pass --allow-mixed-commits if\n"
              f"       you have a specific reason and will state it in the caption.",
              file=sys.stderr)
        return 3

    agg = aggregate(rows)
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    tag = commits[0] if len(commits) == 1 else "MIXED:" + ",".join(commits)

    (out / "T1_main.tex").write_text(latex_main_table(
        agg, a.main_arms, "tab:main",
        rf"Trajectory accuracy. Median over reps; ATE in metres. Commit \texttt{{{tag}}}."))
    (out / "T3_ablation.tex").write_text(latex_ablation_table(
        agg, a.baseline, "tab:ablation",
        rf"Component ablation, medians across sequences. Commit \texttt{{{tag}}}."))

    # Prose ledger: every number the text may quote, with its provenance.
    (out / "numbers.json").write_text(json.dumps({
        "commits": commits,
        "n_rows": len(rows),
        "generated_from": sorted({r["_src"] for r in rows}),
        "cells": {"|".join(k): v for k, v in agg.items()},
    }, indent=2, default=str))

    print(f"commit(s): {', '.join(commits)}")
    print(f"{len(rows)} rows -> {len(agg)} cells")
    for (arm, d, s), c in sorted(agg.items()):
        print(f"  {arm:14s} {d:8s} {s:28s} n={c['n_ok']}/{c['n']} "
              f"ATE_sim3={fmt(c['ate_sim3_rmse'])} ATE_se3={fmt(c['ate_se3_rmse'])} "
              f"s={fmt(c['scale_s'])} fps={fmt(c['pipeline_fps'], 1)}")
    print(f"\nwrote {out}/T1_main.tex, T3_ablation.tex, numbers.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
